---

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
locale: "ru_RU.utf8"
timezone: "Europe/Moscow"
desktop_autostart:
  add:
    - { name: yakuake, exec: /usr/bin/yakuake }  
    - { name: plank, exec: /usr/bin/plank }  
    - { name: fusuma, exec: /usr/local/bin/fusuma }  
    - { name: telegram-desktop, exec: /snap/bin/telegram-desktop }  
    - { name: thunderbird, exec: /usr/bin/thunderbird }  
    - { name: myteam, exec: /snap/bin/myteam }  
    - { name: kitty, exec: /home/shalashik/.local/bin/kitty }  
    - { name: slack, exec: /snap/bin/slack }
  
  remove:
snap_applications:
  - pycharm-professional
  - postman  
  - intellij-idea-ultimate  
  - go  
  - goland  
  - slack  
  - telegram-desktop
  - zoom-client 
