---

- name: Ubuntu desktop environment playbook
  hosts: localhost
  roles:
    # Common roles
    - { role: 1password, become: true }
    - { role: locales, become: true }
    - { role: common, become: true }
    - { role: git }
    - { role: zsh, become: true }
    - { role: ohmyzsh, become: true }  
    - { role: yakuake, become: true }  
    - { role: konsole, become: true }  
    - { role: vim, become: true }  
    # - { role: dotfiles, become: true }
    - { role: java-openjdk, become: true }
    # Server roles
    - { role: docker, become: true }
    - { role: python, become: true }
    - { role: ssh, become: true }
    # Desktop roles
    - { role: desktop, become: true }
    - { role: desktop-cleanup, become: true }
    - { role: desktop-autostart, become: true }
    - { role: arc-theme, become: true }
    - { role: copyq, become: true }
    - { role: dbeaver, become: true }
    - { role: filezilla, become: true }
    - { role: firefox, become: true }
    - { role: geary, become: true }
    - { role: indicator-sysmonitor, become: true }
    - { role: maim, become: true }
    - { role: min, become: true }
    - { role: notepadqq, become: true }
    - { role: remarkable, become: true }
    - { role: remmina, become: true }
    - { role: ripgrep, become: true }
    - { role: rofi, become: true }
    - { role: shutter, become: true }
    - { role: thunderbird, become: true }
    - { role: ultra-flat-icons, become: true }
    - { role: virtualbox, become: true }
    - { role: snap, become: true } 
    # bspwm
    # - { role: sxhkd, become: true }
    # - { role: bspwm, become: true }
    # - { role: bspwm-panel, become: true }
    # - { role: bspwm-environment, become: true }
    # User roles
    # - { role: gulp}
    # - { role: browsersync }
    # - { role: bower }
    # - { role: webpack }
    # HW
    - { role: bose_qc35 }
