---

- name: Install common desktop packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  loop:
    - bleachbit
    - byzanz # screen recording
    - inotify-tools
    - meld # Diff / merge tool
    - cifs-utils
    - mpv
    - pinta # light paint.net equivalent
    - plasma-workspace-wayland    
    - rhythmbox
    - rxvt-unicode-256color
    - tilda # lighter than guake
    - ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
    - vlc
    - wmctrl # to control windows
    - xdotool # to control windows

- name: Install common desktop packages if Ubuntu 16.04
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  loop:
    - fonts-hack-ttf
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Block Ubuntu product search in system host file
  lineinfile: dest=/etc/hosts regexp="^127\.0\.0\.1   productsearch.ubuntu.com$" line="127.0.0.1   productsearch.ubuntu.com" state=present

- name: Ensure that lightdm configuration directory exists
  file: path=/etc/lightdm/lightdm.conf.d state=directory

- name: Disable guest session in lightdm
  copy: src="50-no-guest.conf" dest="/etc/lightdm/lightdm.conf.d/50-no-guest.conf" force=no
