---
- name: clone oh-my-zsh for users
  tags:
    # Suppress warning: [ANSIBLE0006] git used in place of git module
    # Git module doesn't allow us to set `core.autocrlf=input`.
    - skip_ansible_lint
  become: yes
  become_user: '{{ item.user }}'
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: 'git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh'
  args:
    chdir: '{{ item.home }}'
    creates: '.oh-my-zsh'
  with_items: 
    - { user: '{{  ansible_env.USER }}', home: '{{  ansible_env.HOME }}' }
    - { user: root, home: '/root' }

- name: set permissions of oh-my-zsh for users
  become: yes
  file:
    path: '{{ item }}/.oh-my-zsh'
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
    recurse: yes
  with_items: 
    - '/home/{{ ansible_env.USER }}'
    - '/root'

- name: Copy default ZSH config for user root
  copy: 
    src: "kinda-fishy.zsh-theme" 
    dest: "{{ item.home }}/.oh-my-zsh/themes/kinda-fishy.zsh-theme" 
    owner: '{{ item.user }}' 
    group: '{{ item.user }}' 
    force: yes
  with_items:
    - { user: '{{  ansible_env.USER }}', home: '{{  ansible_env.HOME }}' }
    - { user: root, home: '/root' }

- name: write .zshrc for users
  become: yes
  become_user: '{{ item.user }}'
  template:
    src: zshrc.j2
    dest: '{{ item.home }}/.zshrc'
    backup: yes
    mode: 'u=rw,go=r'
  with_items: 
    - { user: '{{  ansible_env.USER }}', home: '{{  ansible_env.HOME }}' }
    - { user: root, home: '/root' }
