---

- name: Configure the Oracle APT key
  apt_key: url={{ item }} state=present
  loop:
    - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - https://www.virtualbox.org/download/oracle_vbox.asc  


- name: Configure the VirtualBox APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present

- name: Install VirtualBox {{ virtualbox.version }}
  apt: pkg=virtualbox-{{ virtualbox.version }} state=present
