---
- name: Install
  apt: 
    pkg: "{{ item }}" 
    state: latest 
  loop:
    - docker.io
    - docker-compose 

- name: Add user to docker group 
  user:
    name: shalashik
    groups: docker
    append: yes

