---
# this playbook doesn't work properly anymore. Need to change it to apply commands below
# systemctl --user disable pulseaudio.socket 
# systemctl --user disable pulseaudio.service 
# /etc/pulse/client.conf: "autospawn = no" "daemon-binary = /bin/true" 
# /etc/pulse/daemon.conf: avoid-resampling = yes; default-sample-rate = 48000  


- name: Edit bluetooth main config
  lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^#ControllerMode'
    line: 'ControllerMode = bredr'
  become: yes

- name: Enable A2DP
  lineinfile:
    path: /var/lib/gdm3/.config/pulse/client.conf
    line: "{{ item }}"
    create: yes
  with_items:
    - "autospawn = no"
    - "daemon-binary = /bin/true"  
  become: yes

- name: Disable pulseaudio startup
  file:
    path: /var/lib/gdm3/.config/systemd/user/sockets.target.wants/pulseaudio.socket 
    state: absent
  become: yes  

- name: Install blueman
  apt: pkg=blueman state=latest update_cache=yes cache_valid_time={{ aptcachetime }}
  become: yes  

  #- name: set gdm owner
  #  file:
  #    path: /var/lib/gdm3/.config/pulse/client.conf
  #    owner: gdm
  #    group: gdm
  #  become: yes
  #
